backend:
  name: github
  repo: mdalzell/mattdalzell.com

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: src/blog
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: tags, label: Tags, widget: list }
      - { name: draft, label: Save As Draft, widget: boolean }
      - { name: body, label: Body, widget: markdown }
  - name: content
    label: Content
    files:
      - label: Home Page
        name: index
        file: src/content/index.md
        fields:
          - { name: title, label: Title, widget: string }
          - { name: body, label: Intro, widget: markdown }
          - {
              name: skills,
              label: Skills,
              widget: object,
              fields:
                [
                  { name: title, label: Title, widget: string },
                  {
                    name: sections,
                    label: Sections,
                    widget: list,
                    fields:
                      [
                        { name: title, label: Title, widget: string },
                        {
                          name: skills,
                          label: Skills,
                          widget: list,
                          fields:
                            [{ name: skill, label: Skill, widget: string }],
                        },
                      ],
                  },
                ],
            }
